SQL3104N  The Export utility is beginning to export data to file "tab4.ixf".

SQL3105N  The Export utility has finished exporting "3008" rows.

SQL3150N  The H record in the PC/IXF file has product "DB2    02.00", date 
"20170422", and time "235847".

SQL3153N  The T record in the PC/IXF file has name "tab4.ixf", qualifier "", 
and source "            ".

SQL3109N  The utility is beginning to load data from file "tab4.ixf".

SQL3110N  The utility has completed processing.  "3008" rows were read from 
the input file.

SQL3221W  ...Begin COMMIT WORK. Input Record Count = "3008".

SQL3222W  ...COMMIT of any database changes was successful.

SQL3149N  "3008" rows were processed from the input file.  "3008" rows were 
successfully inserted into the table.  "0" rows were rejected.

